### ISSUE TITLE
Does multus support PBR (policy base routing)

### ISSUE THREAD

**Issue by tatyakadam** [k8snetworkplumbingwg/multus-cni#1177]
Does multus support PBR (policy base routing)?
If yes is there any reference doc link or network attachment definiton template link for same?

**Comment by nicklesimba** [comment]
Can you explain more about PBR? I am not familiar. Can you also explain why you need this for multus? Thank you!

**Comment by s1061123** [comment]
Currently multus CNI does not have any network specific feature because multus CNI drives other CNI plugin (e.g. macvlan/ipvlan/flannel/cilium and so on) to add network functionality into container. Hence multus expects that such network feature should be implemented as CNI plugin and multus just calls that.

In CNCF's CNI project, there is [sbr](https://www.cni.dev/plugins/current/meta/sbr/) cni plugin, so it may fits to your case.
