### ISSUE TITLE
Any plans to cut a new release?

### ISSUE THREAD

**Issue by mamccorm** [k8snetworkplumbingwg/multus-cni#1253]
Hi there. 

It looks like there have been plenty of active commits to main, but there hasn't been a release cut since May 2023. Has the project any plans to cut a new release tag soon?

**Comment by ibranafis** [comment]
Hi team, we are blocked on a new release for our development work. We need to move from the multus thick plugin to thin plugin because the thick plugin does not have ARM64 support. The thin plugin with this change needs to be consumed by us: https://github.com/k8snetworkplumbingwg/multus-cni/pull/1270 to handle --multus-master-cni-file-name flag. 
This is currently only on the latest master, and there has been no communication of a release.

**Comment by nvollmar** [comment]
@ibranafis thick plugin would work fine on arm64, you'd just need to build an image yourself, or use a 3rd party one.

**Comment by ibranafis** [comment]
@nvollmar, we won't be able to use the unofficial images. Please let us know if there would be a release soon?

**Comment by adrianchiris** [comment]
adding on.

latest tagged version (v4.0.2) cant really be deployed reliably with thin plugin since it does not contain [1] 
and possibly other fixes (did not review ~1yr of commit history) but the one below i hit easily in my setup (restart of multus pod )

[1] https://github.com/k8snetworkplumbingwg/multus-cni/pull/1142

**Comment by mamccorm** [comment]
Any updates? still no new GH release, and plenty of commits?

**Comment by sdwilsh** [comment]
I think this can be closed now: https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v4.1.0
