### ISSUE TITLE
deploy  multus plugin on k8s cluster deployed with juju, the /etc/cni/net.d doesn't exist on the master node?

### ISSUE THREAD

**Issue by hshtel** [k8snetworkplumbingwg/multus-cni#317]
I have deployed kubernetes-core bundle with maas/juju which include flannel as the default cni for the cluster.
and the deployed multus deamonset after that as described in the quick start guide.
```
cat ./images/{multus-daemonset.yml} | kubectl apply -f -
```

I need support for below issues:
* what happened is that the path /etc/cni/net.d existed in the worker nodes and not on the master? 

it is mentioned in the guide that we have to deploy multus before any other plugin, so what is the needed adjustment in my case as flannel is deployed first. in other words how to set up multus to be the main plugin.

**Comment by hshtel** [comment]
knowing that I've tried to change the multus config file 70-multus.conf to 00-multus.conf in the daemonset so no need to adjust it each time a new worker is added, but I got an error and the daemoset will not be executed.

**Comment by dougbtv** [comment]
Just coming across this while cleaning out some backlog... Two things:

1. We changed the quick start style installation to say that you should install your default network plugin first, now (e.g. flannel, calico, weave, etc) -- so that might help.

2. Any chance you would be willing to figure out what the default CNI configuration directory is with juju? ...If that's possible, it might make sense to make a reference deployment for Multus given those parameters.

**Comment by hshtel** [comment]
Thanks for your feedback, and actually the modification you have made will help and it is more convenient to me now. 
for juju default CNI configuration directory, I'm not working on this cluster now and I'm not able to figure it out, sorry.
