### ISSUE TITLE
Setting up a travis job on ppc64le.

### ISSUE THREAD

**Issue by siddheshghadi** [k8snetworkplumbingwg/multus-cni#429]
I am trying to set up a travis job for multus-cni on ppc64le, I have made changes to the amd64 docker file and ppc64le docker file to build on both amd64 and ppc64le, however the open-shift docker file uses image which is amd64 specific and throws "exec format error" when building on ppc64le. Is there any equivalent open-shift image which I can use for ppc64le or is it ok to skip open-shift docker build on ppc64le?

**Comment by s1061123** [comment]
To build ppc64le image, `Dockerfile.ppc64le` https://github.com/intel/multus-cni/blob/master/Dockerfile.ppc64le is the one.

Do you have any reason that want to use Dockerfile.openshift?

**Comment by siddheshghadi** [comment]
No special reason as such, just want to enable travis support on ppc64le. Would the community willing to accept the changes made so that multus-cni builds on both amd64 and ppc64le on travis?

**Comment by s1061123** [comment]
now ppc64 build is done in travis as following:
https://travis-ci.org/intel/multus-cni/jobs/636399685

**Comment by siddheshghadi** [comment]
Currently the build only runs on amd64 platform. What we are looking for is to run it on ppc64le also, by adding arch: ppc64le in travis.yml.

**Comment by s1061123** [comment]
In https://travis-ci.org/intel/multus-cni/jobs/636399685#L441, we build multus with "TARGET=ppc64le" because it makes ppc64 binary with this option, and result is here.

https://hub.docker.com/layers/nfvpe/multus/latest-ppc64le/images/sha256-7d8d831a79d6899b4ffa7b31bdd4844edc94fdc7d9a84da943d60288304c1ad5

It seems to be 'amd64' (from manifest), however, there is ppc binary with ppc centos container actually. Could you please try it?

If you not just want it but you clearly want to run travis CI process in ppc architecture, please let me know why you need to run compile/publish process in ppc?

**Comment by dougbtv** [comment]
@siddheshghadi we have recent improvements which should help you out here, can you try the latest Multus ppc64 build and see if that works for you? Thanks!
