### ISSUE TITLE
Uninstallation procedure / scripts / daemonsets

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/multus-cni#461]
**What would you like to be added**: We'd like a more straight-forward way to uninstall Multus should you decide that you'd like to revert back to your primary default CNI plugin.

**Why is this needed**: It's counter intuitive to have to reconfigure CNI and remove plugins when this could be accomplished by having some scripts or daemonset that reversed the process created by the quick-start / daemonset installation method.

**Comment by s1061123** [comment]
We also need to think the case that uses `clusterNetwork` and `defaultNetworks`, both uses default network as multus CRD.

**Comment by mukesh-dua** [comment]
A more straight forward way would be to check for existence of default/cluster network configuration file in /etc/cni/net.d/. In fact, that should be recommended way for deploying a clusterNetwork.

If the default CNI is added as a Network Attached Definition, then deleting Multus/CRD will leave Cluster unusable. 

I think we also need to take care of CRD deletion during upgrades as that might impact all Network Attached definitions (based on CRD here)

**Comment by jessehu** [comment]
With Multus CNI v3.7.1, after `kubectl delete -f multus-daemonset.yml`, I'm not able to create a normal pod with or without annotation k8s.v1.cni.cncf.io/networks:

`Warning  FailedCreatePodSandBox  114s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e5c6dfb35b19f6fc8c7edeaa1855d62800bb64959e03104a1e4c17343d3390bf": Multus: [default/samplepod33]: error getting pod: Unauthorized`

I think it's because `/etc/cni/net.d/00-multus.conf` is not delete from the worker nodes, but the service account and crd are deleted.  So is there a clean and correct to uninstall Multus CNI?

**Comment by s1061123** [comment]
@jessehu Currently Kubernetes does not provide uninstall CNI plugin, hence we don't have a way to uninstall multus from Kubernetes, kubelet. Actually, CNI plugin is invoked from container runtime, so uninstall CNI plugin should be implemented by container runtime, such as containerd/cri-o, but as far as I looked the document, there is no description how to do that.

So I could say there is no clean/correct way to uninstall multus CNI from Kubernetes at that time and it could be provided from container runtime (I guess each container runtime has each way, so not straight forward...)

**Comment by jessehu** [comment]
Thanks @s1061123. This make sense. A possible solution I can imagine may run a Daemon set to remove the leftover CNI binary and conf file.

**Comment by s1061123** [comment]
@jessehu that could be a one solution, however, none guarantee that it is official because there is no official way, not in CNI community also in container runtime community. In some specific case, you could verify/guarantee some procedure to uninstall CNI plugin, but it is not perfect (i.e. might be only for all pods are already drained).

This repo, multus cni, is to provide just a CNI plugin, not Kubernetes CNI lifecycle management (even though mulutus mainly used in Kubernetes). That is the reason why multus daemonset does not provide uninstall. We cannot provide uninstall procedure for all scenarios/container runtimes with some guarantee.

So if you want to, you could implement your daemonset (based on multus daemonset or from scratch) and use it in your scenario, at your own risk.
