### ISSUE TITLE
Injected PCIDEVICE_INTEL_XXX variable has the bus ids in a random order

### ISSUE THREAD

**Issue by svallala** [k8snetworkplumbingwg/multus-cni#499]
The environment variable injected to the pod is not listing the bus ids in any particular order. If each of these VFs is associated with a different VLAN there is no easy way to MAP and provide this information. How will Application consume these bus ids?

PCIDEVICE_INTEL_COM_SRIOV3_IGBUIO=0000:87:0c.5,0000:87:0b.6,0000:87:0d.0

Multus: v3.4.1
K8s: 1.16.3

**Comment by krishnajs** [comment]
@svallala using the order of device in the environment variable feels like it might break anytime. Can you think of other ways of achieving the same as different environment variables?

**Comment by svallala** [comment]
Adding the network attachment name along with the bus id could be an option. In our platform, we are injecting additional environment variables using CRI, but would be good if a mapping is provided via the environment variable by the plugin.

**Comment by krishnajs** [comment]
@svallala this env is basically handled by SRIOV-DP and not Multus. Order can not be maintained since kublet randomly allocates devices. SRIOV-DP has no access to interface names give in the SRIOV-CNI or multus so it is no possible to append device name to the exposed devices in env. We will look SRIOV-CNI to see if we can add device ID but it needs investigation.
