### ISSUE TITLE
Multus doesn't pass deviceID for clusterNetwork

### ISSUE THREAD

**Issue by Mmduh-483** [k8snetworkplumbingwg/multus-cni#501]
When use "clusterNetwork" of multus and give it the required network attachment name, muluts doesn't pass the deviceID (pci address) to that CNI.

Multus Config:
```
{"cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "logLevel": "debug", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/kubernetes/admin.conf", "clusterNetwork": "antrea" }
```

Network Attachment:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: antrea
  namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/mlnx_sriov_rdma
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "antrea",
    "type": "antrea",
    "ipam": {"type": "host-local"}
}'
```

When add the multus annotation (without k8s.v1.cni.cncf.io/networks annotation) to the pod then it passes the deviceID, which seems not consistent behavior? 
```
...
annotations:
   v1.multus-cni.io/default-network: antrea
...
```
Is this the intended behavior for `clusterNetwork`, or is it a bug?

**Comment by Mmduh-483** [comment]
@moshe010 @adrianchiris @s1061123

**Comment by s1061123** [comment]
@Mmduh-483 , thank you for your report, at first!

This is expected behavior, for now. We cannot use `clusterNetwork` to SR-IOV net-attach-def. To make SR-IOV interface primary, we have various challanges as following:

1) SR-IOV interface does not support various Kubernetes networking features
As you know, SR-IOV interface skips container host network namespace, other than veth, hence various Kubernetes
networking feature (e.g. NAT for service, load-balancer and so on). Hence even though `clusterNetwork` supports
deviceID, we cannot say it is supported.

2) Some Kubernetes pods, which does not have resource annotation at startup, cannot be launched.
Some Kubernetes pods, like CoreDNS pods, are automatically launched at cluster deployment and the pod does not have
such resource requirements/limits in its yaml file. In such case, pods cannot be launched due to SR-IOV CNI error
(e.g. `SRIOV-CNI failed to load netconf: LoadConf(): VF pci addr is required`).

```
    resources:
      requests:
        intel.com/intel_sriov_netdevice: '1'
      limits:
        intel.com/intel_sriov_netdevice: '1'
```

3) Pod cannot be launched if users run out of SR-IOV interfaces, in any case
Just as it is. In such case, user may want to launch pods furthermore, with other CNI plugins (e.g. macvlan),
but for now we don't have such mechanism in network annotation (i.e. second candidate).

But of course it is worth to discuss and provide solutions somehow in community. Let's talk about it in Network Plumbing WG bi-weekly meeting next week, 5/21. I'm going to add it in agenda.

BTW, with `v1.multus-cni.io/default-network` annotation in pod, we can override cluster network interface with any net-attach-def, including SR-IOV, currently. So it might be a workaround for that.

**Comment by adrianchiris** [comment]
Thank you for the detailed response Tomo!

We are looking into hardware offloading an OVN network.
So in this case you could have a "slow" connection to the pod's cluster network via veth pair or a "fast" connection the the pod's cluster network via SR-IOV.

**Comment by s1061123** [comment]
Got it. In this case, I have question.

Q1. Are "slow" and "fast" configuration the same from CNI config point of view?

As far as I know, if we use SR-IOV VF for interface, 'sriov' CNI plugin will be used, but veth case "ovn-kubernetes" in case of ovn?) will be used. This means we need to have two CNI configuration. Do you have any idea for configure?

Q2. IP address assignment between 'fast' pods and 'slow' pods

'sriov' need to use 'ovn' CNI plugin for IPAM (i.e. ip address assignment), otherwise some IP address will be conflicted between 'fast' pod and 'slow' pod...

**Comment by adrianchiris** [comment]
> Q1. Are "slow" and "fast" configuration the same from CNI config point of view?
Same CNI and same CNI config. What differs is the presence of DeviceID.
This is intended for network devices that support switchdev mode, where a VF has a representor which acts similarly to veth pair.

see: https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/ovs_offload.md


> Q2. IP address assignment between 'fast' pods and 'slow' pods
As its the same CNI, there will be no issues
