### ISSUE TITLE
documented release schedule

### ISSUE THREAD

**Issue by howels** [k8snetworkplumbingwg/multus-cni#622]
**What would you like to be added**:

Documented release schedule showing plans for releases in 2021.

**Why is this needed**:

As a long-term spectator who is now considering using Multus as part of a Kubernetes distribution in a large company I am keen to understand the Multus release schedule. I am also concerned about the lack of recent releases and what this may mean for the health of the Multus project.
A documented release schedule would fix both of these problems.

**Comment by martinkennelly** [comment]
@howels Thank you for raising this. I am going to piggy back on this issue.

I believe Multus is moving to NPWG in the next few days. Two folks have asked me for a new release to capture the great work done by @dougbtv and @s1061123 in the last 9 months. WDYT @s1061123 / @dougbtv ?
I think a schedule would also be nice.

**Comment by howels** [comment]
It would be good to see a new release.

**Comment by manuelbuil** [comment]
I am interested in the schedule plans as well

**Comment by dougbtv** [comment]
Thanks for the concern and the question! A while back, we had discussed a release cycle on a regular time period.

Since we will be moving to the Network Plumbing Working Group -- I'd invite you to join our regular meetings to get your say in as well, you can find some information about the meetings here @ https://github.com/k8snetworkplumbingwg/community

That being said, Multus is actively maintained and developed, I assure you. However, we have reached a certain level of stability, and the lack of recent releases are due to the stability, whereas we were more frequently adding releases as core functionality changed greatly.

Additionally -- we actively encourage contributions and participation! We'd be pleased to have you join our maintainer's meeting, you can find more information in our [agenda document](https://www.google.com/url?q=https://docs.google.com/document/d/17-vkuoObBFBb6feXNA7tjTaKr-rs8ea0VTnqvlEdCv8/edit%23&sa=D&source=calendar&ust=1615644143727000&usg=AOvVaw2hlj2nrcqkLeZwCK9ts3iE), and be part of the solution for inclusion in your k8s distribution.

Thanks @howels !

**Comment by dougbtv** [comment]
@howels @manuelbuil @martinkennelly -- we discussed having a release tagged bi-annually if one has not been recently tagged, there's a PR up @ #630 for review. Thanks!

**Comment by dougbtv** [comment]
Additionally we tagged https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v3.7.1 :+1:
