### ISSUE TITLE
Second NIC on GKE

### ISSUE THREAD

**Issue by hyavari** [k8snetworkplumbingwg/multus-cni#623]
I need to add a second interface to some of the specific K8s pods on GKE that need to be accessible directly from public users on the Internet. So I used Multus and defined a Macvlan cni like this:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.162.0.0/20",
        "rangeStart": "10.162.0.100",
        "rangeEnd": "10.162.0.150",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.162.0.1"
      }
    }'
```

10.162.0.1 is the default gateway of my K8s nodes in GCP. So, I imagine that in this case, those pods should have the access to the outside via nodes' valid IP. But in pods, just there is one default gateway that routes the internal pods' traffic. Also, I can't add any route because of the privileges issues.

This is a correct expectation? what might be the issue?

**Comment by hyavari** [comment]
Also, I created a new IP alias for K8s and used that range for Macvlan. In this case, pods on the same node can ping each other on their second interface (Net1), but not pods on a different node(s) or out other VMs. Although there is a default route for the new range in VPC routes.
What I am missing? 

PS: I checked the same issue on GitHub that was solved with "promiscuous" enablement on node's eth0. But this is enabled in the GKE nodes through "IP Forwarding".

**Comment by dougbtv** [comment]
Hello @hyavari -- thanks for contributing this issue.

Unfortunately, Multus is the tool that's used to attach multiple network interfaces to pods, but in the end, it's platform agnostic. So it doesn't know what to do between GKE, or AWS, or `$fill_in_the_blank`. So it's up the user/administrator/etc to configure this kind of scenario.

I will say that macvlan on cloud providers has been known to be tricky, and that AWS (for example) does filter macvlan traffic, so it won't make it from one node to the next.

Something that I have seen some people do is use the bridge CNI, and configure bridges on each host (by hand or automation, or what-have-you) and give those bridges a uniform name, and configure the connectivity on those bridges in advance, and then use that bridge name in the bridge CNI configuration -- if the bridge exists the bridge CNI will use the existing bridge (otherwise it creates a vanilla bridge for you)

However, beyond that, specifically regarding macvlan on GKE is probably outside the scope of Multus itself, and may be better served by the GKE community, or possibly by the CNI maintainers regarding macvlan CNI.
