### ISSUE TITLE
Multus and GKE

### ISSUE THREAD

**Issue by erir910** [k8snetworkplumbingwg/multus-cni#628]
It seems that Multus does not work with GKE, at least not when executing the entrypoint with the flag `--multus-conf-file=auto` since GKE doesn't use a CNI network plugin by default (most probably it uses the `kubenet` network plugin instead but I am not sure). That means that the the host's directory `/etc/cni/net.d` is empty and the line at https://github.com/k8snetworkplumbingwg/multus-cni/blob/f6298a3a294a79f9fbda0b8f175e521799d5f8d7/images/entrypoint.sh#L258 never actually return a conflist file since there is none. I even had a look at the multus container logs and I saw the log `"Attemping to find master plugin configuration, attempt X"` keeps repeating.

Does that mean that Multus can never work since the network plugin isn't set to `cni` in the first place as the kubelet will not follow the same flow of locating the cni plugin conf file and so on and executing the plugin executable?

AFAIK Azure AKS also uses `kubenet` by default, I am not sure if other big vendors do the same. If my assumption is correct that means that Multus can never work for a whole class of managed clusters

**Comment by s1061123** [comment]
See https://github.com/k8snetworkplumbingwg/multus-cni/issues/106

**Comment by erir910** [comment]
@s1061123 The referred issue is about kubeconfig files. I am pretty sure that's not the problem in my case!

**Comment by s1061123** [comment]
As noted in https://github.com/k8snetworkplumbingwg/multus-cni/issues/106#issuecomment-421522729 in my mentioned issue, GKE seems to use `kubenet` as default, so to enable multus you (or GKE) need to change the config to make CNI enable because GKE's Kubernetes is managed by GKE and GKE's network is also managed by GKE, as well as Azure AKS.

If you want to make similar things to multus in GKE, you need to 

- come up with how to do that without multus or
- ask managed Kubernetes provider (GKE, AKS or so) to provide these feature
 
because multus is just a CNI plugin and it is only for Kubernetes configured for CNI plugin. For managed Kubernetes, just ask their provider.

**Comment by erir910** [comment]
@s1061123 thank you for the fast response again. afaik GKE doesn't provide any means currently to set the network plugin to `cni`. I am not sure if this question can be considered off-topic, but is there a way in kubernetes (i.e. within the kubernetes API itself) to know the network namespace path of a pod? I know that the kubelet knows it since it provides it to the CNI plugin. But can a controller or a pod know that value without using some ugly hacks?

**Comment by s1061123** [comment]
@erir910 I'm not sure about GKE and I don't use GKE. Your question is not multus, just for GKE's Kubernetes configuration. Please ask GKE support for that. I have no idea and GKE support must know about it because they manage it.
