### ISSUE TITLE
Remove thick image variant

### ISSUE THREAD

**Issue by champtar** [k8snetworkplumbingwg/multus-cni#750]
**What would you like to be added**:
Remove the new thick image variant

**Why is this needed**:
Thick images are the same a 'normal' images minus entrypoint.sh
Thick images only support 1 arch and are currently not versioned in the registry
We can support both deployment style with just 1 set of images IMO

**Comment by s1061123** [comment]
@maiqueb Any thoughts?

**Comment by maiqueb** [comment]
They're meant to be different, at least that was their goal: the entrypoint based img shouldn't have the binaries for the confi generation, not the controller stuff.

The fact they're the same, is a bug - a different one imo.

**Comment by champtar** [comment]
Does the size difference really justify the maintenance cost ?
If size matter we can start by switching to an alpine base.

**Comment by maiqueb** [comment]
> Does the size difference really justify the maintenance cost ?

Users that want to use the legacy option have exactly what they had before: a widely used / tested in production multus version. Nothing changed there.

New (brave) users that want to jump to the thick-plugin bandwagon can do it; its the users choice when to change from one to the other alternative: that was by design, and was our goal from the start.

I don't mind paying this price until I feel comfortable enough that I won't break existing deployments. 

I have to ask: why does this image bother you ? You're not forced to use it - it's entirely optional.

**Comment by champtar** [comment]
Thick deployment is what's recommended in the README and quick start :)
I was trying to wrap my head around what's the image difference, and the thick image just has 1 less script.
I'm not advocating to have 1 deployment type, just 1 image

**Comment by maiqueb** [comment]
> Thick deployment is what's recommended in the README and quick start :) I was trying to wrap my head around what's the image difference, and the thick image just has 1 less script. I'm not advocating to have 1 deployment type, just 1 image

I've explained what's the purpose, and reasoning behind the 2 images. IMO, the real bug here is the legacy image features the binaries that are meant to exist only inside the thick img. 

BTW: I think you're missing an important detail: the "legacy" img (entrypoint script based) is based on a [centOS 7 docker img](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/images/Dockerfile#L10) - has python installed, plus whatever things its entrypoint script requires. 

The thick option, on the other hand, is based on [ubi8 minimal](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/images/Dockerfile.thick#L10) - it has no python installed, nor it has plenty of other things. The images are actually quite different: it's not only the entrypoint script.

You're probably right that I was a bit to eager to update README / quick start ... It should probably mention the legacy thing. 

@s1061123 / @dougbtv what's your take on this ? I think we should:
- only install the "thin" binary on the "legacy" image
- update the quick start / README to point at the legacy img.

**Comment by champtar** [comment]
I missed the hidden python requirements, which can be quite big, in that case it makes sense to have a thinner thick image ;)
ubi8 is missing arm32 arch, isn't alpine enough ?

**Comment by dougbtv** [comment]
I think we're good to keep thin/thick variants given Miguel's explanation.

Stay tuned for further changes as the thick plugin develops!
