### ISSUE TITLE
Multus interfering with connection to kubernetes services

### ISSUE THREAD

**Issue by rroberts59110** [k8snetworkplumbingwg/multus-cni#837]
I've run into a problem in using Multus-CNI with Weave-net as the default CNI plugin. I have some containers that use CORBA code and I need to have one pod communicate directly with an external device attached to a host with a 10Gb network card. To enable this I am using Multus to provide an additional network interface to one pod. Since this code uses CORBA, I have a CORBA name service running that is represented by a Kubernetes (Rancher K3s) service. If I create a network attachment to this pod using Multus, the pod is unable to see the kubernetes service that provides access to the CORBA naming service. If I remove the annotation for the Network attachment definition, the pod comes up and can see the CORBA naming service. When I add the annotation for the Multus interface (macvlan in this case) back, the pod comes up, the Multus interface is there and can communicate with the external device, but the pod can no longer see the CORBA naming service.
I've successfully done this with Flannel as the default CNI plugin but this doesn't seem to be working with Weave.
Any help or suggestions would be appreciated.

**Comment by dougbtv** [comment]
> but the pod can no longer see the CORBA naming service.

Could it be that the routing for the container is wrong? e.g. what does `ip route` look like when you exec into the pod?

**Comment by rroberts59110** [comment]
It's more complicated than that. Ip route doesn't show a route to the service network and will not. IPs associated with services are virtual IPs and the kube-proxy on each node sets iptables rules to allow pods to reach a service. As I said above if I do not create an additional network attachment to the relevant pod, it sees the Naming service. When I create a network interface with Multus and then create the pod, it can no longer see the naming service. In neither case is a route shown to the service network.

**Comment by s1061123** [comment]
> I've successfully done this with Flannel as the default CNI plugin but this doesn't seem to be working with Weave.

From your comments above, you already find that 'multus with flannel works' and 'multus with weave' does not work. Hence I guess that

- some network config given from weave makes CORBA service unavailable, or
- some network config ginve from flannel makes CORBA service available.

Multus does just invoke delegating CNI plugin (i.e. flannel or weave) and multus does nothing special for each plugins. So you need to check network configuration (e.g. Pod's routing, Pod's iptables and so on, as well as container host side) and try to figure it out.
Some Kubernetes CNI plugin has specific network configuration (such as routing, DNS config and so on) and it may conflicts with multus additional network interface because some CNI plugin does not assume the its use-case with multus.

I am not good at K3s, CORBA, weave and flannel, so hope that someone else will gives good information for the issue.

**Comment by rroberts59110** [comment]
To use multus, you create a custom resource definition of type NetworkAttachmentDefinition. To use this custom resource from a pod(or deployment) you provide an annotation that names the the custom resource you created. If I create the pod without an additional network interface(no annotation in the yaml file), it can reach the CORBA naming service, which is fronted by a kubernetes service. If I use Multus to create an additional network interface on the pod by adding the annotation to the yaml file and recreating the pod, the additional interface is created and works well. However I suddenly cannot reach the the Kubernetes service which provides the CORBA name service. Nothing has changed with the configuration of Weave.
