### ISSUE TITLE
Patchable NetworkAttachmentDefinition

### ISSUE THREAD

**Issue by kossyrev-bg** [k8snetworkplumbingwg/multus-cni#872]
**What would you like to be added**: The ability to patch a NetworkAttachmentDefinition via a standard `patches/patchesStrategicMerge/patchesJson6902` in a kustomization file.

**Why is this needed**: We have a project where we'd like to use one definition file across multiple systems. Certain components of the def (such as cni version, type, mode) are the same across all systems. Others, like `master, name, ipam`, vary from system to system. It would be really convenient to have this one file and just have each system folder only contain a patch that edits the respective components of the def. 

From what I can tell, this isn't possible because the `config` portion of the spec is defined as a string. If we could define it as a normal dict, all of the above patch methods would Just Work(TM).

1. Why does the config have to be a string instead of a normal, patchable, dict?
2. Is there a way to achieve the above without an enhancement to multus that I am unaware of? I don't want to use bash scripts and the like because I want to keep everything within the kustomize file framework.

**Comment by dougbtv** [comment]
I understand where you're coming from @kossyrev-bg -- however, there's a few challenges. One of which is that JSON is native to CNI plugins, and Multus being a meta plugin, talks JSON between CNI plugins.

YAML is more "Kubernetes-ish" of course, and easier for humans to write. But since the structure of CNI plugins that Multus can delegate to is partially arbitrary, it's hard to know all of the structures in advance.

Converting this yaml internally in Multus would require a high level of understanding of the backing mechanism for the conversion, and it would be hard to make sure that the yaml is perfect for conversion into json.

We are interested in having a more yaml-focused experience for users, but, for now with CNI 1.0 being JSON focused, this isn't likely in the short term.

If you'd like to discuss the standard that we follow in further detail, please join us for the K8s Network Plumbing Working Group call: https://github.com/k8snetworkplumbingwg/community
