### ISSUE TITLE
Multus-cni is not supported in Azure even if Azure Managed K8S as well

### ISSUE THREAD

**Issue by subratpatel1992** [k8snetworkplumbingwg/multus-cni#892]
Tried install k8s on the top of the Azure vm enabled with Accelerated Network  (Mellnox) .Checked with Microsoft Azure team ,as per them  Multus CNI is not supported in Azure even if Azure Managed K8S as well .But which works for AWS .Could you please verify from your end or Help me out to setup on Azure vm .

**Comment by s1061123** [comment]
Hi,

Multus is 'CNI plugin' which can run Kubernetes deployment. From support point of view, we don't have any supported list for cloud platform because multus depends on deployment network. We only know about multus and we don't know what the cloud platform network. For each cloud provider designed Kubernetes deployment with their use-case, so we only say 'please ask each platform provider to support multus or not'.

In case of AWS, multus team does not support AWS platform (as well as not support Azure/gke and others), actually. AWS team supports mentions 'multus is supported (by AWS)'.  So we don't have any info about AWS and don't have any help from AWS.
