### ISSUE TITLE
Deployments in releases do not use image tag of release.

### ISSUE THREAD

**Issue by jklare** [k8snetworkplumbingwg/multus-cni#896]
**What happend**:
When trying to deploy from release tag v3.9.1 with the deployment file included in the repository for that tag, you get the latest build image from master.

**What you expected to happen**:
When using a deployment file from a release of this repository, you should also get the fitting image built from that state of the repo.

**How to reproduce it (as minimally and precisely as possible)**:
Try to deploy e.g. the "multus-daemonset-thick-plugin.yml" from tag v3.9.1

**Anything else we need to know?**:
-

**Environment**:
freshly installed k8s on ubuntu 20.04 with kubeadm

If you agree that this should be fixed, i am happy to provide a couple of MRs for the v3.9 releases.

**Comment by s1061123** [comment]
thank you for the information, @jklare .

If you can fix by automated way (modify image tag in [github action CI pipeline](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/.github/workflows/image-push-release.yml)), we'd be happy to merge. Do you come up with a way for that?

If not, we may keep it because we don't want to modify for each time manually. In addition, these deployment file is mainly desgined for 'quickstart'. We will modify daemonset soon to explicitly mentions the purpose of the yaml.

**Comment by jklare** [comment]
I think fixing it in an automated way would be great and maybe i can figure out a way to do that. To get started here, i would need a bit more information on how you automatically create the release tags/branches. Is there a job somewhere in the background that creates those tags whenever you agree that there should be a release or is are those tags created manually? Same question for the releases themselves, are those somehow created by a bot that has access to this git repo or is this done by hand?
Cheers

**Comment by s1061123** [comment]
As I added the anchor, once we tagged the repository, [github action CI pipeline](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/.github/workflows/image-push-release.yml) runs for release. This build container image and push it to ghcr.io. So you need to modify this file or add another file to do that.

**Comment by jklare** [comment]
Ok, that means that we would need to move from a release tag to a release branch first, because otherwise it's not possible to add the release specific commit which changes the deployment files to point to the release specific tagged images. I think auto generating this commit will be pretty easy, since in the end it's just a simple `sed -i 's/multus-cni\:thick/multus-cni\:v3.9.1-thick-amd64/g' deployments/multus-daemonset-thick.yml` where "v3.9.1" would be the ${{ steps.docker_meta.outputs.tags }} i guess. Would you consider moving to release branches instead of tags?

**Comment by s1061123** [comment]
- I don't agree that we use branch instead of tag for version. If we use branch, then each version can append more commit and it causes ambiguous versioning (3.9.1 -> 3.9.1 again -> 3.9.1 again again as well as 3.9.2)
- In CI pipeline, we don't commit any code, so `sed -i ` seems not be a feasible way (with above reason)

As I noted https://github.com/k8snetworkplumbingwg/multus-cni/pull/897, we provide deployment yaml for its quickstart, hence we expect that user should modify it to fit to user environment. So let's make it close at present.
Any idea to improve this, is always welcome.

**Comment by jklare** [comment]
I don't think that branching for a release would automatically lead to an ambigous versioning. Looking at other projects, branching for a release is rather a usual thing, since whenever a code repository contains certain files or artifacts that are only needed within a release, those can and should only be added to the release branch. Obviously such a workflow requires everybody involved to not change the application code within the branch, but just work on the "example"/"documentation" files, like deployment.yml file examples or things alike. Those "release" branches are usually needed anyways to allow building bug fix releases and backports for security critical fixes from newer versions.
Maybe a way to go here would be to have a "v3.9-stable" (or something similar) branch, which would contain all the tags for v3.9.X releases. Within this branch, we could then also modify the example deployment files to point the the v3.9.x based images.

**Comment by s1061123** [comment]
In addition, we don't make release pages as well: https://github.com/k8snetworkplumbingwg/multus-cni/releases
