### ISSUE TITLE
Any enhancement multus support on cloud Aws or Azure infuture .

### ISSUE THREAD

**Issue by subratust** [k8snetworkplumbingwg/multus-cni#902]
Tried install k8s on the top of the Azure vm enabled with Accelerated Network (Mellnox) .Checked with Microsoft Azure team ,as per them Multus CNI is not supported in Azure .So any enhancement/improvement   on multus-cni plugin which  support in cloud platform like Azure or Aws in future .Please let us know .

**Comment by s1061123** [comment]
Hi,

Multus is 'CNI plugin' which can run Kubernetes deployment. From support point of view, we don't have any supported list for cloud platform because multus depends on deployment network. We only know about multus and we don't know what the cloud platform network. For each cloud provider designed Kubernetes deployment with their use-case, so we only say 'please ask each platform provider to support multus or not'. Multus-CNI cannot support AWS and Azure because multus is CNI plugin. 

Kubernetes does not support AWS and Azure (i.e. Kubernetes does not do something special for that). AWS and Azure supports Kubernetes. Multus is same. 

Regarding AWS, AWS already mentioned that EKS supports multus.
https://aws.amazon.com/jp/blogs/containers/amazon-eks-now-supports-multus-cni/

In case of AWS, multus team does not support AWS platform (as well as not support Azure/gke and others), actually. AWS team supports mentions 'multus is supported (by AWS)'. So we don't have any info about AWS and don't have any help from AWS.
